### ISSUE TITLE
IllegalStateException on add item in history

### ISSUE THREAD

**Issue by alirezaafkar** [lapism/SearchView#160]
`java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.shatelland.namava/databases/search_history_database.db
                                                                           at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
                                                                           at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1312)
                                                                           at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
                                                                           at com.lapism.searchview.SearchHistoryTable.getLastItemId(SearchHistoryTable.java:78)
                                                                           at com.lapism.searchview.SearchHistoryTable.addItem(SearchHistoryTable.java:53)
                                                                           at com.lapism.searchview.SearchHistoryTable.addItem(SearchHistoryTable.java:40)`

**Comment by lapism** [comment]
Hi,
in 3.5  I have added a lot of pull requests so It can be from it. I will check it ASAP.

**Comment by lucasfernog** [comment]
Can you describe the exact steps to reproduce it? I can't do it with my app, but I will check it today.

**Comment by alirezaafkar** [comment]
It happens on item click (history or suggestion), on click I add new item to history table and some times this happens

**Comment by lucasfernog** [comment]
removed some unnecessary open(); close(); and changed dbHelper.close() to db.close()
https://drive.google.com/file/d/0B68KMT9Qdi9aZFE3UDRRSjZfRXM/view?pref=2&pli=1 
but I still can't reproduce the exception so i don't know if it works.

**Comment by lapism** [comment]
Same thing. I was not able to reproduce your exception in sample app.

**Comment by alirezaafkar** [comment]
For happens some times, not always.

**Comment by lapism** [comment]
OK.  I will be trying more.

**Comment by onclicklistener** [comment]
Same to me,it's happened quite often.

**Comment by lapism** [comment]
Guys, can you describe when it happens exactly?

**Comment by RJFares** [comment]
I found a fix. 
I moved my searchview's findViewById in my activity from onCreate to onPostCreate.
(Actually I removed the bind with butterknife and bound it manually in onPostCreate, same thing).
This has to do with the way the history db was written. 
I never user sqlite for db management but if someone can find out a fix it'd be better.

**Comment by RJFares** [comment]
+1
It was happening to me often. Then I moved my searchview's findViewById in my activity from onCreate to onPostCreate, now it happens rarely, but it still does. I will look into it and report back.

**Comment by RJFares** [comment]
The problem comes from database not being properly closed/opened from SearchHistoryTable.
It happens randomly and not often so tracking the source of the problem was not possible.

There is a solution, although not as conventional (got it from a post in stackoverflow). It's a quote of a google engineer.
http://groups.google.com/group/android-developers/msg/74ee967b2fcff770

> Android made a deliberate design decision that is can seem surprising, to just give up on the whole idea of applications cleanly exiting and instead let the kernel clean up their resources. After all, the kernel needs to be able to do this anyway. Given that design, keeping anything open for the entire duration of a process's life and never closing it is simply not a leak. It will be cleaned up when the process is cleaned up.

As you are using the SQLiteOpenHelper singleton, there is no problem of concurrency, that's also why isDbLockedByOtherThreads is deprecated since API Level 16.

If you just drop multiple opening and closing and only do it once this should fix the issue.
