### ISSUE TITLE
IllegalArgumentException: Scrapped or attached views may not be recycled.

### ISSUE THREAD

**Issue by michalciolek** [lapism/SearchView#165]
After update to 3.5 version I get:

```
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
 at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5231)
 at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:7697)
 at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:7682)
 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:546)
 at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3315)
 at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2843)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at android.support.v7.widget.CardView.onMeasure(CardView.java:211)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at android.view.View.measure(View.java:18796)
 at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1085)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
 at android.view.View.measure(View.java:18796)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
 at android.view.Choreographer.doCallbacks(Choreographer.java:670)
 at android.view.Choreographer.doFrame(Choreographer.java:606)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.lo
```

Replication error:
1. input text: "tes"
2. show suggestion
3. add letter t ("test")
4. crash

**Comment by michalciolek** [comment]
Ok, I found solution. This is my fault. I have "custom" searchAdapter and when I wanted to update search suggestions I always called:  `notifyDataSetChanged();` (like in old version) but in 3.5 we have to call something like that:
```
    public void setData(List<SearchItem> data)
    {
        if (mResultList == null) {
            mResultList = data;
            notifyDataSetChanged();
        }
        else {
            int previousSize = mResultList.size();
            int nextSize = data.size();
            mResultList = data;
            if (previousSize == nextSize && nextSize != 0)
                notifyItemRangeChanged(0, previousSize);
            else if (previousSize > nextSize) {
                if (nextSize == 0)
                    notifyItemRangeRemoved(0, previousSize);
                else {
                    notifyItemRangeChanged(0, nextSize);
                    notifyItemRangeRemoved(nextSize - 1, previousSize);
                }
            }
            else {
                notifyItemRangeChanged(0, previousSize);
                notifyItemRangeInserted(previousSize - 1, nextSize);
            }
        }
    }
```

**Comment by lucasfernog** [comment]
Actually it's Google fault, notifyDataSetChanged() with android:animateLayoutChanges set to true causes the exception

**Comment by luisvega16** [comment]
@lucasfernog Can you tell me how I can set the android:animateLayoutChanges set to false in the RecyclerView of the SearchView?  I can't find it. Thanks ;)

**Comment by MarcinusX** [comment]
So is there any way to update suggestion list?

**Comment by lapism** [comment]
setSuggestionsList from SearchAdapter should work.

**Comment by MarcinusX** [comment]
Wow, I've just realized that I was calling notifyPropertyChanged() alongside with setSuggestionsList and that was causing the problem... Calling only setSuggestionsList works perfectly, thanks!

**Comment by avinashkolluru** [comment]
Based on @lucasfernog comment I had to get rid of the notifyDataSetChanged(). Changed the setData() to something like this

`public void setData(List<SearchItem> data) {
        if (mResultList.size() == 0) {
            mResultList = data;
            if(data.size() != 0) {
                notifyItemRangeInserted(0, data.size());
            }
...
`
