### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by alizarei95** [lapism/SearchView#174]
after using this i faced with this error

Caused by: java.lang.NoSuchFieldError: No static field cardView of type I in class Lcom/lapism/searchview/R$id; or its superclasses (declaration of 'com.lapism.searchview.R$id' appears in /data/app/com.example.farasoo.myapplication-1/base.apk)

supportlibrary 24.2.1

**Comment by lapism** [comment]
Hi, please check the sample app, everything works there.

**Comment by Yogeeshvh** [comment]
I followed the sample app, but still getting the same error....
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mathrusoft.infogo/com.mathrusoft.infogo.activity.ActivityMain}: android.view.InflateException: Binary XML file line #11: Binary XML file line #43: Error inflating class com.lapism.searchview.SearchView
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #43: Error inflating class com.lapism.searchview.SearchView
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                       at com.mathrusoft.infogo.activity.ActivityMainBase.onCreate(ActivityMainBase.java:21)
                                                       at com.mathrusoft.infogo.activity.ActivityMain.onCreate(ActivityMain.java:104)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
please fix this ASAP.....
