### ISSUE TITLE
IllegalArgumentException searchView adapter

### ISSUE THREAD

**Issue by vise950** [lapism/SearchView#177]
Hi i have a last version of library but i have a problem with searchView adapter.

this is code (i use pastebin because here code indentation dont't work well)
http://pastebin.com/R0ZTp3cH

and this is locgat
`java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                               at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5234)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:5181)
                                                                               at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:7426)
                                                                               at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleAllViews(RecyclerView.java:8704)
                                                                               at android.support.v7.widget.RecyclerView.setAdapterInternal(RecyclerView.java:944)
                                                                               at android.support.v7.widget.RecyclerView.setAdapter(RecyclerView.java:915)
                                                                               at com.lapism.searchview.SearchView.setAdapter(SearchView.java:635)
                                                                               at com.dev.nicola.allweather.MainActivity$5$1$1.run(MainActivity.java:365)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

the problem happens on mSearchView.setAdapter(mSearchAdapter);

**Comment by lucasfernog** [comment]
check sample app, you need to setAdapter only if getAdapter returns null i think

**Comment by Gericop** [comment]
I need a way to be able to set the adapter again because I have only one Activity and I want to change the adapter for different Fragments. Currently this is not available as it always throws the given exception when setting the adapter. Is there any way to fix this?

**Comment by lapism** [comment]
Method setAdapter does not work ?

**Comment by vise950** [comment]
this is old work code with autocomplete google result
https://hastebin.com/howohovido.java
Sorry but now use https://github.com/arimorty/floatingsearchview

Il giorno lun 15 mag 2017 alle ore 21:27 lapism <notifications@github.com>
ha scritto:
