### ISSUE TITLE
NoSuchFieldError inflating SearchView

### ISSUE THREAD

**Issue by robertoestivill** [lapism/SearchView#19]
I'm experiencing the following issue in my application

```
E/AndroidRuntime(19323): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.application/com.application.MyActivity}: android.view.InflateException: Binary XML file line #47: Error inflating class com.lapism.searchview.SearchView
E/AndroidRuntime(19323): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
E/AndroidRuntime(19323): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
E/AndroidRuntime(19323): 	at android.app.ActivityThread.access$800(ActivityThread.java:155)
E/AndroidRuntime(19323): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
E/AndroidRuntime(19323): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19323): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(19323): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(19323): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19323): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(19323): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(19323): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(19323): Caused by: android.view.InflateException: Binary XML file line #47: Error inflating class com.lapism.searchview.SearchView
E/AndroidRuntime(19323): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime(19323): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
E/AndroidRuntime(19323): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime(19323): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime(19323): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime(19323): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime(19323): 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
E/AndroidRuntime(19323): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
E/AndroidRuntime(19323): 	at com.application.MyActivity.onCreate(MvpViewBaseActivity.java:49)
E/AndroidRuntime(19323): 	at android.app.Activity.performCreate(Activity.java:6010)
E/AndroidRuntime(19323): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
E/AndroidRuntime(19323): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
E/AndroidRuntime(19323): 	... 10 more
E/AndroidRuntime(19323): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(19323): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime(19323): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime(19323): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime(19323): 	... 21 more
E/AndroidRuntime(19323): Caused by: java.lang.NoSuchFieldError: No static field recyclerView of type I in class Lcom/lapism/searchview/R$id; or its superclasses (declaration of 'com.lapism.searchview.R$id' appears in /data/app/com.bitflow.beta-2/base.apk)
E/AndroidRuntime(19323): 	at com.lapism.searchview.SearchView.initView(SearchView.java:98)
E/AndroidRuntime(19323): 	at com.lapism.searchview.SearchView.<init>(SearchView.java:78)
E/AndroidRuntime(19323): 	at com.lapism.searchview.SearchView.<init>(SearchView.java:72)
E/AndroidRuntime(19323): 	... 24 more
```

The layout is

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:fitsSystemWindows="true">

  <android.support.v4.widget.DrawerLayout
    android:id="@+id/home_drawer"

    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.AppBarLayout
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

      <android.support.v7.widget.Toolbar
        android:id="@+id/home_toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:layout_scrollFlags="scroll|enterAlways|snap"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

      <LinearLayout
        android:id="@+id/home_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        android:orientation="vertical" />

    </android.support.design.widget.AppBarLayout>

    <android.support.design.widget.NavigationView
      android:id="@+id/home_navigation"
      android:layout_width="wrap_content"
      android:layout_height="match_parent"
      android:layout_gravity="start"
      android:fitsSystemWindows="true"
      app:headerLayout="@layout/nav_header"
      app:menu="@menu/drawer_view" />

  </android.support.v4.widget.DrawerLayout>

  <com.lapism.searchview.SearchView
    android:id="@+id/home_search_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:search_style="classic"
    app:search_theme="light"  />

</FrameLayout>
```

Any ideas what might be wrong here?  
I have tried the example app from Play Store and works just fine.

Thanks

Motorola Moto X 2nd Gen 2014
Android 5.1 stock
compileSdkVersion 23
buildToolsVersion "23.0.1"
targetSdkVersion 23
support libs 23.1.1

**Comment by ultraon** [comment]
1. Did you try to download library and connect as module?
2. After rebuild project, can you find out com.lapism.searchview.R.java in the project? (also id subclass)

**Comment by lapism** [comment]
Application from Play Store has exactly same version of library like last one -  1.3.9. One important thing is that you should use layout from sample application - classic or with design library. In your layout you are using FrameLayout with DrawerLayout. I have never tried this combination so I am not really sure if it works well.

**Comment by robertoestivill** [comment]
@ultraon 
1) No, I will give that a try when I have some time
2) `com.lapism.searchview.R` is generated, but not `com.lapism.searchview.R.id.recyclerView` which is the ID of the recycler view that is missing when inflating the view. Any clues what might be happening here? 

![screen shot 2016-01-04 at 09 35 45](https://cloud.githubusercontent.com/assets/3728545/12089732/b7be5a7e-b2c6-11e5-99a3-8266e9e02b4e.png)

@lapism 
I will take a look and play around with the layouts. However, shouldn't we be able to just add a SearchView anywhere we need to? Is the SearchView explicitly dependent on the layout view siblings ?

Thanks both for the fast answers

**Comment by lapism** [comment]
Yes, you are right about that. In next BIG release ( which I am doing right now ) I will change that. But it will take some time.
If you take a look on SearchView layout, then you will see that layout has "match_parent" for width and height. The reason is because it has transparent grey view under SearchView. And this can be source of your problems. I did it exactly like Play Store and it took me a while to figure out how to do it, so yes, it depends on the layout.

**Comment by robertoestivill** [comment]
I see. Thanks for the heads up. I will play around with the layout and comment back on my results.

Thanks again

**Comment by robertoestivill** [comment]
The problem was another library that contained a layout file with the same `search_view.xml` name.
While is not specifically a library problem, is always nice to prefix all your library resources to avoid collisions with other libraries. 

You can easily accomplish this by using the `resourcePrefix` gradle feature documented [here](http://tools.android.com/tech-docs/new-build-system)
```
android {
  resourcePrefix 'mylib_'
}
```

Thanks for your help

**Comment by lapism** [comment]
You are welcome. You can see in sources that I have already added a prefix almost everywhere.

**Comment by matteozajac** [comment]
I have this same problem now. Maybe you can change id from "recyclerView" to something more unique?

**Comment by lapism** [comment]
Hi, why not. I will do it in next release.

**Comment by matteozajac** [comment]
Sounds perfect!
