### ISSUE TITLE
Conflict with FloatingActionButton?

### ISSUE THREAD

**Issue by hpsoar** [lapism/SearchView#190]
when I add SearchView to the dependencies of my project, it the the following error and crash on running.

Don't quite know why.

BR.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.beacon.searchdemo/com.beacon.searchdemo.MainActivity}: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
             at android.app.ActivityThread.access$1100(ActivityThread.java:221)
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
             at android.os.Handler.dispatchMessage(Handler.java:102)
             at android.os.Looper.loop(Looper.java:158)
             at android.app.ActivityThread.main(ActivityThread.java:7233)
             at java.lang.reflect.Method.invoke(Native Method)
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
          Caused by: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton
             at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
             at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
             at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
             at com.beacon.searchdemo.MainActivity.onCreate(MainActivity.java:31)
             at android.app.Activity.performCreate(Activity.java:6876)
             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
             at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
             at android.os.Handler.dispatchMessage(Handler.java:102) 
             at android.os.Looper.loop(Looper.java:158) 
             at android.app.ActivityThread.main(ActivityThread.java:7233) 
             at java.lang.reflect.Method.invoke(Native Method) 
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
          Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton
             at android.view.LayoutInflater.createView(LayoutInflater.java:657)
             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
             at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
             at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
             at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
             at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
             at com.beacon.searchdemo.MainActivity.onCreate(MainActivity.java:31) 
             at android.app.Activity.performCreate(Activity.java:6876) 
             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
             at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
             at android.os.Handler.dispatchMessage(Handler.java:102) 
             at android.os.Looper.loop(Looper.java:158) 
             at android.app.ActivityThread.main(ActivityThread.java:7233) 
             at java.lang.reflect.Method.invoke(Native Method) 
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
          Caused by: java.lang.reflect.InvocationTargetException
             at java.lang.reflect.Constructor.newInstance(Native Method)
             at android.view.LayoutInflater.createView(LayoutInflater.java:631)
             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
             at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
             at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
             at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
             at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
             at com.beacon.searchdemo.MainActivity.onCreate(MainActivity.java:31) 
             at android.app.Activity.performCreate(Activity.java:6876) 
             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
             at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
             at android.os.Handler.dispatchMessage(Handler.java:102) 
             at android.os.Looper.loop(Looper.java:158) 
             at android.app.ActivityThread.main(ActivityThread.java:7233) 
             at java.lang.reflect.Method.invoke(Native Method) 
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
          Caused by: java.lang.NoSuchMethodError: No direct method <init>(Landroid/widget/ImageView;Landroid/support/v7/widget/AppCompatDrawableManager;)V in class Landroid/support/v7/widget/AppCompatImageHelper; or its super classes (declaration of 'android.support.v7.widget.AppCompatImageHelper' appears in /data/app/com.beacon.searchdemo-1/base.apk)
             at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:133)
             at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:110)
             at java.lang.reflect.Constructor.newInstance(Native Method) 
             at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
             at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
             at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
             at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
             at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
             at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
             at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
             at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
             at com.beacon.searchdemo.MainActivity.onCreate(MainActivity.java:31) 
             at android.app.Activity.performCreate(Activity.java:6876) 
             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
             at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
             at android.os.Handler.dispatchMessage(Handler.java:102) 
             at android.os.Looper.loop(Looper.java:158) 
             at android.app.ActivityThread.main(ActivityThread.java:7233) 
             at java.lang.reflect.Method.invoke(Native Method)

**Comment by lapism** [comment]
Check if you have last version of support libraries in your project. I will update library with API 25 very soon.
