### ISSUE TITLE
elevation on sibling AppBarLayout "hide" SearchView

### ISSUE THREAD

**Issue by loki666** [lapism/SearchView#201]
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/overview_coordinator_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:elevation="4dp">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_scrollFlags="scroll|enterAlways"
            android:background="?attr/colorPrimary"
            android:minHeight="?attr/actionBarSize"
            android:theme="@style/Toolbar"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    </android.support.design.widget.AppBarLayout>

    <FrameLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"/>

    <com.lapism.searchview.SearchView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="com.lapism.searchview.SearchBehavior" />

</android.support.design.widget.CoordinatorLayout>

**Comment by brunomassa** [comment]
add this to searchview.

`android:elevation="4dp"`

**Comment by loki666** [comment]
not better, it makes the inflation crash

`
11-29 16:09:04.675 25182-25182/net.volcanomobile.modplayer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: net.volcanomobile.modplayer, PID: 25182
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{net.volcanomobile.modplayer/net.volcanomobile.modplayer.modules.domain.view.DownloadModulesActivity}: android.view.InflateException: Binary XML file line #70: Binary XML file line #70: Error inflating class com.lapism.searchview.SearchView
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                              Caused by: android.view.InflateException: Binary XML file line #70: Binary XML file line #70: Error inflating class com.lapism.searchview.SearchView
                                                                              Caused by: android.view.InflateException: Binary XML file line #70: Error inflating class com.lapism.searchview.SearchView
                                                                              Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                                                                                 at net.volcanomobile.modplayer.modules.domain.view.DownloadModulesActivity.onCreate(DownloadModulesActivity.java:42)
                                                                                 at android.app.Activity.performCreate(Activity.java:6664)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.CardView.setMaxCardElevation(float)' on a null object reference
                                                                                 at com.lapism.searchview.SearchView.setElevation(SearchView.java:705)
                                                                                 at android.view.View.<init>(View.java:4654)
                                                                                 at android.view.ViewGroup.<init>(ViewGroup.java:578)
                                                                                 at android.widget.FrameLayout.<init>(FrameLayout.java:92)
                                                                                 at android.widget.FrameLayout.<init>(FrameLayout.java:87)
                                                                                 at com.lapism.searchview.SearchView.<init>(SearchView.java:141)
                                                                                 at com.lapism.searchview.SearchView.<init>(SearchView.java:137)
`

**Comment by brunomassa** [comment]
try put searchview inside appbar layout.

**Comment by brunomassa** [comment]
the solutio is to put this:

`app:elevation="4dp"`

and not this:

`android:elevation="4dp"`

in appbarlayout and searchview

**Comment by loki666** [comment]
app:elevation on AppBarLayout, doesnt cast the shadow

app:elevation on SearchView doesn't crash anymore, but is still hidden when android:elevation is set on the AppBarLayout (I'm seeing the keyboard, but not the SearchView)

**Comment by brunomassa** [comment]
the problem is in method setelevation of searchview.

If you set elevation in xml it returns null on method, and if you set elevation using method the searchview not elevate.

I will try to find a way to fix but if anyone result this please send a pull request.

**Comment by lapism** [comment]
I will try to fix it ASAP ...

**Comment by ratanoff** [comment]
Confirm, I have the same issue!

**Comment by RustamG** [comment]
@lapism Any news on that?

**Comment by lapism** [comment]
No yet. I do not have time for this project but in two weeks I hope I will ...

**Comment by boswelja** [comment]
Experiencing the same issue here, adding android:elevation causes the aforementioned error, and app:elevation has no effect :/

**Comment by lapism** [comment]
Ok, so I did not find the way how to fix this. Maybe I should rewrite CoordinatorLayout.Behavior ...

**Comment by boswelja** [comment]
What if we just wrapped the coordinatorlayout and searchview in a framelayout?

**Comment by lapism** [comment]
Yeah that is possible but in this way it will not scroll with appbar.
