### ISSUE TITLE
Force close on scroll

### ISSUE THREAD

**Issue by alirezaafkar** [lapism/SearchView#212]
`
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.design.widget.AppBarLayout$Behavior.getTopAndBottomOffset()' on a null object reference
                                                                           at com.lapism.searchview.SearchBehavior.needsToAdjustSearchBar(SearchBehavior.java:130)
                                                                           at com.lapism.searchview.SearchBehavior.onNestedPreScroll(SearchBehavior.java:74)
                                                                           at com.lapism.searchview.SearchBehavior.onNestedPreScroll(SearchBehavior.java:16)
`

**Comment by alirezaafkar** [comment]
I think it's because I've coordinate layout without AppBarLayout inside it

**Comment by lapism** [comment]
I will remove default behavior in next release...but I have a new job so I do not know when.

**Comment by lapism** [comment]
For 4.1 release.
