### ISSUE TITLE
Crash App

### ISSUE THREAD

**Issue by volkdown** [lapism/SearchView#215]
Hello! I put layout in your view as stated in the description.
<com.lapism.searchview.SearchView
        android:id="@+id/searchview_mainscreen"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
When I run the application and it crashes
```
android.view.InflateException: Binary XML file line #8: Error inflating class com.lapism.searchview.SearchView
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5275)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
                                                                          Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.lapism.searchview.SearchView
```

With what it can be connected? Thanks in advance for your reply

**Comment by lapism** [comment]
Check sample, it needs to be in AppBarLayout. This Behavior will be changed in version 4.1.
