### ISSUE TITLE
Issue with some phones (unable to start activity)

### ISSUE THREAD

**Issue by Dahnark** [lapism/SearchView#255]
In a LG G2 I am getting this issue. When the user put the app in background and come to the app after a few time.

In my phone I can't reproduce it.

Log:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.MyApp/com.company.MyApp.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5349)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
at android.os.Parcel.readListInternal(Parcel.java:2522)
at android.os.Parcel.readList(Parcel.java:1655)
at com.lapism.searchview.SearchView$e.<init>(SearchView.java:1242)
at com.lapism.searchview.SearchView$e$1.a(SearchView.java:1222)
at com.lapism.searchview.SearchView$e$1.createFromParcel(SearchView.java:1219)
at android.os.Parcel.readParcelable(Parcel.java:2246)
at android.os.Parcel.readValue(Parcel.java:2146)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2540)
at android.os.Parcel.readSparseArray(Parcel.java:1868)
at android.os.Parcel.readValue(Parcel.java:2203)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
at android.os.BaseBundle.unparcel(BaseBundle.java:221)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:871)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2030)
at android.app.Activity.onRestoreInstanceState(Activity.java:1036)
at android.app.Activity.performRestoreInstanceState(Activity.java:991)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1161)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2304)
... 10 more
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference
at android.os.Parcel.readListInternal(Parcel.java:2522)
at android.os.Parcel.readList(Parcel.java:1655)
at com.lapism.searchview.SearchView$e.<init>(SearchView.java:1242)
at com.lapism.searchview.SearchView$e$1.a(SearchView.java:1222)
at com.lapism.searchview.SearchView$e$1.createFromParcel(SearchView.java:1219)
at android.os.Parcel.readParcelable(Parcel.java:2246)
at android.os.Parcel.readValue(Parcel.java:2146)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2540)
at android.os.Parcel.readSparseArray(Parcel.java:1868)
at android.os.Parcel.readValue(Parcel.java:2203)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
at android.os.BaseBundle.unparcel(BaseBundle.java:221)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:871)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2030)
at android.app.Activity.onRestoreInstanceState(Activity.java:1036)
at android.app.Activity.performRestoreInstanceState(Activity.java:991)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1161)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2304)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5349)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

CUSTOM_DATA=
PHONE_MODEL=LG-D802
BRAND=lge
ANDROID_VERSION=5.0.2

**Comment by lapism** [comment]
Thanks. I will fix it ASAP.

**Comment by lapism** [comment]
I hope it will be fixed in 5.0.

**Comment by Dahnark** [comment]
CUSTOM_DATA=
APP_VERSION_NAME=1.0.8
BRAND=lge
USER_COMMENT=null
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{com.videumcorp.leagueoflegendschampionmasteryandchestlookup/com.videumcorp.leagueoflegendschampionmasteryandchestlookup.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1960)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1985)
at android.app.ActivityThread.access$600(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1151)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4476)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.os.Parcel.readListInternal(Parcel.java:2105)
at android.os.Parcel.readList(Parcel.java:1422)
at com.lapism.searchview.SearchView$e.<init>(SearchView.java:1242)
at com.lapism.searchview.SearchView$e$1.a(SearchView.java:1222)
at com.lapism.searchview.SearchView$e$1.createFromParcel(SearchView.java:1219)
at android.os.Parcel.readParcelable(Parcel.java:1992)
at android.os.Parcel.readValue(Parcel.java:1854)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2123)
at android.os.Parcel.readSparseArray(Parcel.java:1576)
at android.os.Parcel.readValue(Parcel.java:1911)
at android.os.Parcel.readMapInternal(Parcel.java:2094)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1225)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1670)
at android.app.Activity.onRestoreInstanceState(Activity.java:1027)
at android.app.Activity.performRestoreInstanceState(Activity.java:999)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1102)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1938)
... 11 more
java.lang.NullPointerException
at android.os.Parcel.readListInternal(Parcel.java:2105)
at android.os.Parcel.readList(Parcel.java:1422)
at com.lapism.searchview.SearchView$e.<init>(SearchView.java:1242)
at com.lapism.searchview.SearchView$e$1.a(SearchView.java:1222)
at com.lapism.searchview.SearchView$e$1.createFromParcel(SearchView.java:1219)
at android.os.Parcel.readParcelable(Parcel.java:1992)
at android.os.Parcel.readValue(Parcel.java:1854)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2123)
at android.os.Parcel.readSparseArray(Parcel.java:1576)
at android.os.Parcel.readValue(Parcel.java:1911)
at android.os.Parcel.readMapInternal(Parcel.java:2094)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1225)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1670)
at android.app.Activity.onRestoreInstanceState(Activity.java:1027)
at android.app.Activity.performRestoreInstanceState(Activity.java:999)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1102)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1938)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1985)
at android.app.ActivityThread.access$600(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1151)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4476)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:583)
at dalvik.system.NativeStart.main(Native Method)

ANDROID_VERSION=4.0.4
PHONE_MODEL=LG-E615f

I think is the same issue, but I give you this crash. Maybe it has new info about this crash.

Will it be fixed in 5.0?

ETA of 5.0?

**Comment by lapism** [comment]
I take a look on it. I hope so...

**Comment by lapism** [comment]
I hope there will be a new version 5.0.0-alpha1 after this weekend.
