### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dahnark** [lapism/SearchView#290]
One user send me this crash report. It is different of the last one.

USER_COMMENT=
ANDROID_VERSION=4.4.2
APP_VERSION_NAME=2.1.0
BRAND=Neuimage
PHONE_MODEL=NIT-805Q
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.MyApp/com.company.MyApp.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5341)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.os.Parcel.readListInternal(Parcel.java:2364)
at android.os.Parcel.readList(Parcel.java:1585)
at com.lapism.searchview.SearchView$e.<init>(SearchView.java:1242)
at com.lapism.searchview.SearchView$e$1.a(SearchView.java:1222)
at com.lapism.searchview.SearchView$e$1.createFromParcel(SearchView.java:1219)
at android.os.Parcel.readParcelable(Parcel.java:2111)
at android.os.Parcel.readValue(Parcel.java:2020)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2382)
at android.os.Parcel.readSparseArray(Parcel.java:1742)
at android.os.Parcel.readValue(Parcel.java:2077)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
at android.os.Bundle.unparcel(Bundle.java:249)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1818)
at android.app.Activity.onRestoreInstanceState(Activity.java:948)
at android.app.Activity.performRestoreInstanceState(Activity.java:920)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1140)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
... 11 more
java.lang.NullPointerException
at android.os.Parcel.readListInternal(Parcel.java:2364)
at android.os.Parcel.readList(Parcel.java:1585)
at com.lapism.searchview.SearchView$e.<init>(SearchView.java:1242)
at com.lapism.searchview.SearchView$e$1.a(SearchView.java:1222)
at com.lapism.searchview.SearchView$e$1.createFromParcel(SearchView.java:1219)
at android.os.Parcel.readParcelable(Parcel.java:2111)
at android.os.Parcel.readValue(Parcel.java:2020)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2382)
at android.os.Parcel.readSparseArray(Parcel.java:1742)
at android.os.Parcel.readValue(Parcel.java:2077)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
at android.os.Bundle.unparcel(Bundle.java:249)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1818)
at android.app.Activity.onRestoreInstanceState(Activity.java:948)
at android.app.Activity.performRestoreInstanceState(Activity.java:920)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1140)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2429)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5341)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
at dalvik.system.NativeStart.main(Native Method)

**Comment by boswelja** [comment]
Library version? Is it reproducible?

**Comment by lapism** [comment]
Yes. I need library version ... btw. I need to upload alpha version of 5.0.0 so maybe error will not be there anymore.

**Comment by Dahnark** [comment]
@boswelja @lapism how can I check library version? I dont know how to reproduce, I ask to my users but they never reply me xD. The app never crashes for me so I don't know if it is a specific error on some Android version, phone brand, etc.

My dependencies:

![image](https://user-images.githubusercontent.com/7463564/29036636-87af67de-7ba0-11e7-91b8-02cda7a97405.png)

**Comment by boswelja** [comment]
@Dahnark you added the library, you should know which version it is. It's the numbers at the end of your compile / implementation line in your apps build.gradle

**Comment by Dahnark** [comment]
@boswelja there you have all my dependencies. If you talk about support library, I have the lastest stable 26+

**Comment by boswelja** [comment]
@Dahnark I was talking about the searchview library, which is 4.0. Hopefully the issue will be fixed when @lapism uploads 5.0.0-alpha1 properly

**Comment by Dahnark** [comment]
I am going to update my app to Play Store with some translation files, this 5.0 is going to be stable? to wait to add it to my app when it isn't  in alpha.

**Comment by boswelja** [comment]
@Dahnark it will be stable eventually, but the next few releases will probably be alpha or beta

**Comment by lapism** [comment]
5.0.0-alpha1 is out. And CHANGELOG will be ASAP. Btw. check the README.

**Comment by Dahnark** [comment]
@lapism implementation still doesn't work for me, it takes some time to appear for us?

**Comment by lapism** [comment]
Probably. https://bintray.com/lapism/maven/searchview/5.0.0-alpha1

**Comment by Dahnark** [comment]
This can be closed, I have stopped to receive this crash with alpha3!
