### ISSUE TITLE
Crash (same ID in hierarchy)

### ISSUE THREAD

**Issue by Dahnark** [lapism/SearchView#294]
USER_COMMENT=
ANDROID_VERSION=4.4.4
APP_VERSION_NAME=2.1.8
BRAND=Huawei
PHONE_MODEL=HUAWEI Y550-L01
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.app/com.company.app.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchView. Make sure other views do not use the same id.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2264)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
at android.app.ActivityThread.access$1100(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5333)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchView. Make sure other views do not use the same id.
at android.view.View.onRestoreInstanceState(View.java:12856)
at com.lapism.searchview.SearchView.onRestoreInstanceState(SearchView.java:1180)
at android.view.View.dispatchRestoreInstanceState(View.java:12832)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2639)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.View.restoreHierarchyState(View.java:12810)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1769)
at android.app.Activity.onRestoreInstanceState(Activity.java:968)
at android.app.Activity.performRestoreInstanceState(Activity.java:940)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2242)
... 11 more
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchView. Make sure other views do not use the same id.
at android.view.View.onRestoreInstanceState(View.java:12856)
at com.lapism.searchview.SearchView.onRestoreInstanceState(SearchView.java:1180)
at android.view.View.dispatchRestoreInstanceState(View.java:12832)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2639)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.View.restoreHierarchyState(View.java:12810)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1769)
at android.app.Activity.onRestoreInstanceState(Activity.java:968)
at android.app.Activity.performRestoreInstanceState(Activity.java:940)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1138)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2242)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
at android.app.ActivityThread.access$1100(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5333)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
at dalvik.system.NativeStart.main(Native Method)

**Comment by Dahnark** [comment]
USER_COMMENT=
ANDROID_VERSION=5.1
APP_VERSION_NAME=2.2.0
BRAND=lge
PHONE_MODEL=LG-X220
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.company.app/databases/search_history_database.db
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1342)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1285)
at com.lapism.searchview.h.a(SearchHistoryTable.java:117)
at com.lapism.searchview.b$1.publishResults(SearchAdapter.java:183)
at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5647)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by lapism** [comment]
Thanks. I will fix it in next version. I hope...

**Comment by Dahnark** [comment]
Thank @lapism, I am going to check alpha4, can I see a detailed changelog?

**Comment by lapism** [comment]
Sorry, It is not uploaded yet :)

**Comment by Dahnark** [comment]
Yeah I just got this:

Error:(71, 20) Failed to resolve: com.lapism:searchview:5.0.0-alpha4

And I have gone to check bintray hahah.

**Comment by lapism** [comment]
It is uploaded now.

**Comment by Dahnark** [comment]
SearchView Alpha4

ANDROID_VERSION=4.4.2
APP_VERSION_NAME=2.2.2
BRAND=Huawei
PHONE_MODEL=T1-701u
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.app/com.company.app.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchView. Make sure other views do not use the same id.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2347)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
at android.app.ActivityThread.access$1100(ActivityThread.java:143)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5398)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchView. Make sure other views do not use the same id.
at android.view.View.onRestoreInstanceState(View.java:12848)
at com.lapism.searchview.SearchView.onRestoreInstanceState(SearchView.java:1184)
at android.view.View.dispatchRestoreInstanceState(View.java:12824)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2639)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.View.restoreHierarchyState(View.java:12802)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1801)
at android.app.Activity.onRestoreInstanceState(Activity.java:972)
at android.app.Activity.performRestoreInstanceState(Activity.java:943)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1141)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
... 11 more
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchView. Make sure other views do not use the same id.
at android.view.View.onRestoreInstanceState(View.java:12848)
at com.lapism.searchview.SearchView.onRestoreInstanceState(SearchView.java:1184)
at android.view.View.dispatchRestoreInstanceState(View.java:12824)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2639)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2647)
at android.view.View.restoreHierarchyState(View.java:12802)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1801)
at android.app.Activity.onRestoreInstanceState(Activity.java:972)
at android.app.Activity.performRestoreInstanceState(Activity.java:943)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1141)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
at android.app.ActivityThread.access$1100(ActivityThread.java:143)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5398)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
at dalvik.system.NativeStart.main(Native Method)

**Comment by Dahnark** [comment]
Is this a library bug or a bug in my code?

**Comment by Dahnark** [comment]
I am getting a lot of ACRA report of this. Is there any way to fix it myself?

**Comment by lapism** [comment]
Check your code, but I will add search_ prefix to every id.

**Comment by Dahnark** [comment]
@lapism I changed all searchview IDs in java (mainactivity and fragment) and the xml. Still getting ACRA report of this.

USER_COMMENT=
ANDROID_VERSION=5.1.1
APP_VERSION_NAME=2.2.3
BRAND=samsung
PHONE_MODEL=SM-J320FN
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.app/com.company.app.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchViewNewID. Make sure other views do not use the same id.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
at android.app.ActivityThread.access$1000(ActivityThread.java:218)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6934)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchViewNewID. Make sure other views do not use the same id.
at android.view.View.onRestoreInstanceState(View.java:15063)
at com.lapism.searchview.SearchView.onRestoreInstanceState(SearchView.java:1184)
at android.view.View.dispatchRestoreInstanceState(View.java:15039)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3192)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.View.restoreHierarchyState(View.java:15017)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2297)
at android.app.Activity.onRestoreInstanceState(Activity.java:1204)
at android.app.Activity.performRestoreInstanceState(Activity.java:1149)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1190)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
... 10 more
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchViewNewID. Make sure other views do not use the same id.
at android.view.View.onRestoreInstanceState(View.java:15063)
at com.lapism.searchview.SearchView.onRestoreInstanceState(SearchView.java:1184)
at android.view.View.dispatchRestoreInstanceState(View.java:15039)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3192)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3198)
at android.view.View.restoreHierarchyState(View.java:15017)
at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2297)
at android.app.Activity.onRestoreInstanceState(Activity.java:1204)
at android.app.Activity.performRestoreInstanceState(Activity.java:1149)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1190)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
at android.app.ActivityThread.access$1000(ActivityThread.java:218)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6934)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

What could be the problem? I am calling him from MainActivity to setup it and from fragment to setup the adapter, I should only call from fragment?

**Comment by lapism** [comment]
Maybe. Try to call it only in Activity or Fragment and check if your XML does not have views with same IDs.

**Comment by Dahnark** [comment]
Really in version 4.0 I have that code and it was working. BTW I removed all on the Activity and now it is only in the Fragment.

**Comment by lapism** [comment]
Let me release a new version and we will see :-).

**Comment by lapism** [comment]
Probably after this weekend.

**Comment by Dahnark** [comment]
@lapism is it possible to change the filter state programmatically?

instead of search.getFiltersStates().get(0);

Something like: search.setFiltersStates().get(0).enabled(true/false);

**Comment by Dahnark** [comment]
I got a new crash report of this and in a version of my app that is only using the fragment to call the searchview

**Comment by Dahnark** [comment]
Before you release this weekend the new version, is this fixed?

**Comment by Dahnark** [comment]
I installed Crashlytics so I have more data about this error (phone, Android version, etc). Do you need it?

**Comment by lapism** [comment]
Sure. Just send me this on my email here. And btw. I am not really sure what I should fix and what has been fixed already. I need to take a look on everything here.

**Comment by Dahnark** [comment]
@lapism where can I get your email?

**Comment by Dahnark** [comment]
For me I have two problems:
- This crash.
- No suggestion list in the first search, second search works perfectly.

**Comment by PashkinAlexey** [comment]
I have the same crush in my app. I use Search in fragments, and it crushs after i push home button, use other apps, my app destroys, and I come to my app again.

java.lang.RuntimeException: Unable to start activity ComponentInfo{lenremont.crm.ru.courier/lenremont.crm.ru.courier.MainActivity}: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchView. Make sure other views do not use the same id.
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2470)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2532)
 at android.app.ActivityThread.access$900(ActivityThread.java:169)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
 at android.os.Handler.dispatchMessage(Handler.java:111)
 at android.os.Looper.loop(Looper.java:194)
 at android.app.ActivityThread.main(ActivityThread.java:5562)
 at java.lang.reflect.Method.invoke(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:372)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.view.View$BaseSavedState instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/searchView. Make sure other views do not use the same id.
 at android.view.View.onRestoreInstanceState(View.java:13825)
 at com.lapism.searchview.SearchView.onRestoreInstanceState(SearchView.java:1214)
 at android.view.View.dispatchRestoreInstanceState(View.java:13801)
 at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3018)
 at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3024)
 at android.view.View.restoreHierarchyState(View.java:13779)
 at android.support.v4.app.Fragment.restoreViewState(Fragment.java:500)
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1445)
 at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
 at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3217)
 at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
 at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
 at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
 at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
 at lenremont.crm.ru.courier.MainActivity.onStart(MainActivity.java:453)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1228)
 at android.app.Activity.performStart(Activity.java:5991)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2433)
 ... 10 more

**Comment by lapism** [comment]
Are you using Alpha6?

**Comment by PashkinAlexey** [comment]
yep

**Comment by lapism** [comment]
Ok, so I am going to check it this weekend.

**Comment by PashkinAlexey** [comment]
ok, if i would fix it by myself i would write here about it

**Comment by lapism** [comment]
Ok

**Comment by PashkinAlexey** [comment]
i am sure that it is associated with [that](https://developer.android.com/training/basics/activity-lifecycle/recreating.html)

**Comment by Dahnark** [comment]
@PashkinAlexey your URL is redirecting me to this: https://developer.android.com/guide/components/activities/activity-lifecycle.html

How can I check the section "recreating"?

**Comment by PashkinAlexey** [comment]
if (savedInstanceState != null) in your onCreate or onViewStateRestored methods.
if savedInstanceState  is null - your activity creates as new, if not null - your activity trying to restore it's state.

**Comment by PashkinAlexey** [comment]
To avoid my crash problem i use 
`@Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(requestFragment.saveInstanceState(new Bundle()));
    }`
After that You can handle this bundle on recreate and use it as you wish.

**Comment by HusseinElFeky** [comment]
@Dahnark @PashkinAlexey If you use Android Studio, try searching all your files for `@+id/searchView` by pressing `Ctrl` + `Shift` + `F`. Make sure there are no redundant views with the same id that are added in the same hierarchy in your activity (even if they were in different layouts, what matters is if they are in the same hierarchy). Did you try that?

**Comment by Dahnark** [comment]
I did it. It is a library problem and I think that the problem is related with pashkin link

**Comment by HusseinElFeky** [comment]
Do you use `SearchView` inside a fragment? If yes, can you check [this](https://stackoverflow.com/questions/22499272/android-illegalargumentexception-wrong-state-class-if-the-app-was-background-fo)?

**Comment by HusseinElFeky** [comment]
Do you use `SearchView` inside a fragment? If yes, can you check [this](https://stackoverflow.com/questions/22499272/android-illegalargumentexception-wrong-state-class-if-the-app-was-background-fo)? In that case, the exception occurred because the fragment was getting recreated and thus creating another instance of `SearchView` with the same id.

**Comment by HusseinElFeky** [comment]
@Dahnark Have you got this working or are you still testing?

**Comment by Dahnark** [comment]
I haven't this problem never, my users got it. so I have to check your code, implement it to play store, wait to a lot of users get my app and then check Crashlytics. This week I had no time because I was moving a lot of debris from my house. I will check this tonight or tomorrow.

Does OP know how to reproduce it to test personally instead of wait to get Crashlytics reports?

**Comment by Dahnark** [comment]
@HusseinElFeky but if I implement this: `if(myFragment == null)`

And using the navigation drawer to change from one fragment to another one, does not it stop to work?

         
```
case 0:
         fragmentManager = getMyFragmentManager();
         fragmentTransaction = fragmentManager.beginTransaction();
         myFragment = new MyFragment();
         fragmentTransaction.replace(R.id.frameLayoutListFragment, myFragment);
         fragmentTransaction.commit();
case 1:
         etc.
```

Should I use

```
case 0:
         if(myFragment == null){
                fragmentManager = getMyFragmentManager();
                fragmentTransaction = fragmentManager.beginTransaction();
                myFragment = new MyFragment();
                fragmentTransaction.replace(R.id.frameLayoutListFragment, myFragment);
                fragmentTransaction.commit();
         }
                break;
```

**Comment by Dahnark** [comment]
ah and this issue was not appearing in version 4.0

**Comment by HusseinElFeky** [comment]
I didn't test that solution, but I only sent you that link in case you can have any insight to this issue. Well, I would say test your new implementation first before uploading it to Play Store. Try rotating your screen many times, use navigation drawer to switch between fragments, go to home screen, open any other app, use it for a while, then go back to your app and see if everything still works as expected, etc. If everything works, then try publishing a new version on Play Store and check Crashlytics. But first let me check something in v4.0 and I will reply again.

**Comment by HusseinElFeky** [comment]
Alright, so while checking v4.0, I found no difference at all in `onRestoreInstanceState`, `onSaveInstanceState` and `SavedState` itself, so it **should** not be a new issue in v5.0. Try what I said, and I hope it gets fixed.

**Comment by Dahnark** [comment]
my app haven't enabled screen rotation but maybe this is the problem: https://stackoverflow.com/a/8127813/3262021

**Comment by Dahnark** [comment]
Or maybe this:
```
@Override
    public void onDestroyView() {
        super.onDestroyView();
        Fragment fragment = getFragmentManager().findFragmentById(R.id.frameLayoutListFragment);
        FragmentTransaction fragmentTransaction = getActivity().getSupportFragmentManager().beginTransaction();
        fragmentTransaction.remove(fragment);
        fragmentTransaction.commitAllowingStateLoss();
    }
```

**Comment by HusseinElFeky** [comment]
The link you posted is already implemented in this library, while for `onDestroyView` do you call that in your code or is it just a solution that you are thinking to implement?

**Comment by Dahnark** [comment]
I implemented it in my fragment, hope it fixes this problem. Really I did a lot of things like have my app a lot of hours in the background, open and close via multitasking, open and close with the back button, etc. I can't get this crash on my phone and emulators.

Even enabling autorotate just to force this crash is not provoking the crash...

**Comment by HusseinElFeky** [comment]
Yeah, I also get this type of crashes a lot while I never get it at all, not in this library though. Well I hope it gets fixed. Until then, tell us the news when users install your update.

**Comment by Dahnark** [comment]
it is not working, it still crashes

**Comment by HusseinElFeky** [comment]
Which solution did you implement (my link or `onDestroyView` or both? and is it mandatory to put that SearchView inside your fragment? The optimal fast and easy solution would be to put it in your activity.

**Comment by Dahnark** [comment]
onDestroyView

But if I want to have different suggestion list for each fragment how can I have only it in the activity?

**Comment by HusseinElFeky** [comment]
It's easy, just `setSuggestionsList` each time you change your fragment, but it depends. Do you switch between fragments a lot? If yes, then that solution won't be efficient, otherwise you should do that.

**Comment by Dahnark** [comment]
but I have a lot of views in app bar xml that I change programmatically inside the fragment like images, and only fails the searchview. Are you sure that this problem is not in the library?

**Comment by HusseinElFeky** [comment]
I am not sure. @lapism should check.

**Comment by Dahnark** [comment]
@HusseinElFeky really the only thing I can do is to use the default Android SearchView and check if it has this problem

**Comment by HusseinElFeky** [comment]
@Dahnark Yeah, if I were you, I would have done the same. OK 👍

**Comment by Dahnark** [comment]
@HusseinElFeky I will wait to get a @lapism comment about if he can fix it and if not I will try to release a version with normal SearchView.

**Comment by HusseinElFeky** [comment]
@Dahnark I updated my app with v5.0.0-alpha6, and I have just got some crashes like you exactly. I never got it before in v3.8 and v4.0, so it is definitely a bug in v5.0.

FYI, I used it in an activity, not inside a fragment like you, but my app doesn't rotate as well. So in both cases, that bug still occurs. I really hope this gets fixed soon because more crashes means lower ratings.

**Comment by HusseinElFeky** [comment]
@Dahnark I updated my app with v5.0.0-alpha6, and I have just got some crashes like you exactly. I never got it before in v3.8 and v4.0, so it is definitely a bug in v5.0.

FYI, I used it in an activity, not inside a fragment like you, but my app doesn't rotate as well. So in both cases, that bug will still occur. I really hope this gets fixed soon because more crashes means lower ratings.

**Comment by Dahnark** [comment]
Yeah, if I will tell you about lower ratings in my app even with the app working and with no crashes... at this moment in my app there are two really important crashes, this crash, and [onQueryTextChange crash](https://github.com/lapism/SearchView/issues/309).

This last problem maybe is created by me but I can't reproduce it.

**Comment by HusseinElFeky** [comment]
My only issue now is this crash. I didn't use v5.0-alpha6 though. I implemented this library directly to my app so that I can merge my pull request in the source code as well. I didn't face an issue in `onQueryTextChange` though, so yeah maybe.

**Comment by HusseinElFeky** [comment]
@Dahnark I think [that](https://stackoverflow.com/questions/3542333/how-to-prevent-custom-views-from-losing-state-across-screen-orientation-changes) has something to do with the problem. Read Nick Street's comment on Qberticus's answer there. I think I might create another pull request tomorrow implementing Kobor42's solution instead. I just hope @lapism responds because he has been away for a while. Any thoughts?

**Comment by Dahnark** [comment]
@HusseinElFeky yeah, I passed that link with the kobor42 solution yesterday, in that thread there are 3 or 4 different solutions. Maybe one of them works.

This [link ](http://trickyandroid.com/saving-android-view-state-correctly/)has been commented in the kobor52 answer.

But if alpha 4.0 didn't have this error, what has changed?

@lapism have you read that StackOverflow thread?

**Comment by lapism** [comment]
Sorry guys, I have a life so I have not read anything from here yet. ... ASAP

**Comment by HusseinElFeky** [comment]
I'm currently working on that. I understood the reason causing it. In my case, I had two SearchViews in the same activity, but each one had its own setting. So as the crash log explained, both of them had the same childs with the same ids. @Dahnark In your case, I think when switching between fragments, SearchView still saved its state? I'm not sure of that, but that's my thought. Anyway, I'm fixing it right now. I will make a new pull request either after few hours or tomorrow morning.

**Comment by Dahnark** [comment]
I am only calling at this moment the searchview from only one fragment (in future other fragments maybe call it for different purposes)

**Comment by HusseinElFeky** [comment]
Well when you switch between fragments and return to the same fragment, I believe a new `SearchView` instance is created ignoring the last saved `SearchView` as what the log explains. Anyway I should have finally fixed this issue, but first I will upload it to Play Store tomorrow and will see in my crash reports if it still occurs or not. If no crash is found, I will make a pull request probably after tomorrow. 👍

**Comment by Dahnark** [comment]
@HusseinElFeky BTW the problem should be in the change from 4.0 to 5.0, so checking these changes the problem should be reverted.

**Comment by HusseinElFeky** [comment]
@Dahnark Although I definitely agree with you about that, when I compared both versions, there were many stuff changed in the middle, so I couldn't know what new change caused this issue. However my fix should already solve that problem. I already do that in every custom view I create, and there was no problem in it, so it should be hopefully fixed. I have just updated my app now. I will wait till tomorrow to see if that problem still occurs.

**Comment by HusseinElFeky** [comment]
and it's fixed! @Dahnark Let me know if you still have any issue with that. @lapism Can you release alpha7? 🎉

**Comment by HusseinElFeky** [comment]
and it's fixed! @Dahnark Let me know if you still have any issue with that. @lapism I think alpha7 is ready to be released. 🎉

**Comment by Dahnark** [comment]
Perfect! I am going to upload my app with alpha7 when it is released.

**Comment by lapism** [comment]
@HusseinElFeky I am going to check everything you have sent. After that I will release probably this weekend.

**Comment by HusseinElFeky** [comment]
OK great.

**Comment by Dahnark** [comment]
@lapism is there a ETA for alpha7?

**Comment by Dahnark** [comment]
Really I have this hurry because I am going to spend some money to get an adword coupon (it expires soon) and I would like to advertise my app without this crash.

**Comment by lapism** [comment]
Give me a half of hour

**Comment by Dahnark** [comment]
Thank you @lapism !

**Comment by lapism** [comment]
Released.

**Comment by Dahnark** [comment]
I can confirm this is fixed for me, I will close it.
