### ISSUE TITLE
Crash coz of FlexboxLayout in version 5.0.0-alpha4

### ISSUE THREAD

**Issue by EdwardQuixote** [lapism/SearchView#299]
- After implementing SearchView in my Fragment Layout, the fragment can't even load.
- I checked the code to find FlexboxLayout wasn't imported successfully in class "SearchView.java"
- Error Log:
` Caused by: android.view.InflateException: Binary XML file line #101: Binary XML file line #101: Error inflating class com.google.android.flexbox.FlexboxLayout
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                    at com.lapism.searchview.SearchView.initView(SearchView.java:199)
                                                                                    at com.lapism.searchview.SearchView.<init>(SearchView.java:119)
                                                                                    at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                    at com.smartapplications.smartapp.Fragments.FragSignUpStep3.onCreateView(FragSignUpStep3.java:92) 
                                                                                    at android.app.Fragment.performCreateView(Fragment.java:2236) 
                                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:978) 
                                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153) 
                                                                                    at android.app.BackStackRecord.run(BackStackRecord.java:800) 
                                                                                    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562) 
                                                                                    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:487) 
                                                                                    at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                    at android.os.Looper.loop(Looper.java:207) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5763) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) `

**Comment by lapism** [comment]
Please read this issue #298. You have to add FlexBox and CardView dependecy to your main app.

**Comment by EdwardQuixote** [comment]
@lapism Worked. Thanks.
