### ISSUE TITLE
Crash on historyD

### ISSUE THREAD

**Issue by msecilmis** [lapism/SearchView#337]

**Comment by msecilmis** [comment]
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.birohcek.booker/databases/search_history_database.db
                                                                         at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
                                                                         at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1709)
                                                                         at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1686)
                                                                         at com.lapism.searchview.SearchHistoryTable.addItem(SearchHistoryTable.java:51)
                                                                         at com.lapism.searchview.SearchHistoryTable.addItem(SearchHistoryTable.java:35)
                                                                         at HomeFragment$7.onSearchItemClick(HomeFragment.java:216)
                                                                         at com.lapism.searchview.SearchAdapter$ResultViewHolder$1.onClick(SearchAdapter.java:221)
                                                                         at android.view.View.performClick(View.java:5721)
                                                                         at android.view.View$PerformClick.run(View.java:22620)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7409)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by msecilmis** [comment]
Also you should consider using room

https://developer.android.com/training/data-storage/room/index.html

**Comment by lapism** [comment]
I know ROOM but you can create your own adapter with ROOM library.

**Comment by prajapatiravi257** [comment]
Any hack to prevent this exception
