### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by filipedelimabrito** [lapism/SearchView#339]
I have the following exception when starting activity:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx.xxx.android/xxx.xxx.android.app.MainActivity}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.lapism.searchview.SearchView
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.app.ActivityThread.main(ActivityThread.java:5728)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                   Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class com.lapism.searchview.SearchView
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at xxx.xxx.android.app.chatlist.ChatListFragment.onCreateView(ChatListFragment.kt:16)
                      at android.app.Fragment.performCreateView(Fragment.java:2236)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:978)
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                      at android.app.BackStackRecord.run(BackStackRecord.java:800)
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562)
                      at android.app.FragmentController.execPendingActions(FragmentController.java:325)
                      at android.app.Activity.performStart(Activity.java:6324)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2529)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5728) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                   Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.lapism.searchview.SearchView
                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                      at xxx.xxx.android.app.chatlist.ChatListFragment.onCreateView(ChatListFragment.kt:16) 
                      at android.app.Fragment.performCreateView(Fragment.java:2236) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:978) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:800) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562) 
                      at android.app.FragmentController.execPendingActions(FragmentController.java:325) 
                      at android.app.Activity.performStart(Activity.java:6324) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2529) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5728) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance(Native Method)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                      at xxx.xxx.android.app.chatlist.ChatListFragment.onCreateView(ChatListFragment.kt:16) 
                      at android.app.Fragment.performCreateView(Fragment.java:2236) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:978) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:800) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562) 
                      at android.app.FragmentController.execPendingActions(FragmentController.java:325) 
                      at android.app.Activity.performStart(Activity.java:6324) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2529) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5728) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                   Caused by: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class android.widget.ImageView
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at com.lapism.searchview.SearchView.initView(SearchView.java:880)
                      at com.lapism.searchview.SearchView.<init>(SearchView.java:125)
                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                      at xxx.xxx.android.app.chatlist.ChatListFragment.onCreateView(ChatListFragment.kt:16) 
                      at android.app.Fragment.performCreateView(Fragment.java:2236) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:978) 
                      at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153) 
                      at android.app.BackStackRecord.run(BackStackRecord.java:800) 
                      at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1562) 
                      at android.app.FragmentController.execPendingActions(FragmentController.java:325) 
                      at android.app.Activity.performStart(Activity.java:6324) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2529) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5728) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                   Caused by: android.view.InflateException: Binary XML file line #31: Error inflating class android.widget.ImageView
                      at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
```

Looks like there is a problem when inflating an ImageView in the library.

**Comment by lapism** [comment]
I will release new version until Christmas . But it looks like you should check your code and not my library.

**Comment by filipedelimabrito** [comment]
This is happening when I tried to use SearchView...
