### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by FaimMithani** [lapism/SearchView#84]
Fast text entry generates index out of bound exception 

java.lang.IndexOutOfBoundsException: setSpan (12 ... 13) ends beyond length 9
                                                                        at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:349)
                                                                        at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:77)
                                                                        at android.text.SpannableString.setSpan(SpannableString.java:46)
                                                                        at com.lapism.searchview.adapter.SearchAdapter.onBindViewHolder(SearchAdapter.java:125)
                                                                        at com.lapism.searchview.adapter.SearchAdapter.onBindViewHolder(SearchAdapter.java:25)
                                                                        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5471)
                                                                        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5504)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4741)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2625)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1621)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:742)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:607)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
                                                                        at android.support.v7.widget.CardView.onMeasure(CardView.java:206)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1621)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:742)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:607)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:668)
                                                                        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:735)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1621)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:742)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:607)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
                                                                        at android.view.View.measure(View.java:16842)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5374)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1621)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:742)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:607)
                                                                        at android.view.View.measure(View.java:16842)
                                                                    	at android.view.Vi

**Comment by lapism** [comment]
Ok, which version? In 2.2 is a bug.

**Comment by FaimMithani** [comment]
yes.It is in 2.2 version

**Comment by lapism** [comment]
Why people do not read README....you should use newer 3.0.2 and check sample project ! 2.2 has adapter bug.
